name: Send repository dispatch event

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  trigger-event:
    runs-on: ubuntu-latest
    steps:
      - name: Fire event
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer 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" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/gardito-git/target/dispatches \
            -d '{"event_type":"dispatch-event"}'